# Generated by Django 4.1.3 on 2025-01-17 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0003_remove_regi_hashpass'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='regi',
            new_name='registers',
        ),
    ]
