# Generated by Django 4.1.3 on 2025-01-17 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0005_remove_buyers_userpassword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='buyers',
            new_name='contacts',
        ),
    ]
