# Generated by Django 4.1.3 on 2025-01-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0006_rename_buyers_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('useremail', models.CharField(max_length=255)),
                ('userphone', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('select', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
            ],
        ),
    ]
