# Generated by Django 4.1.3 on 2025-01-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0007_bookers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookers',
            name='date',
            field=models.DateTimeField(max_length=255),
        ),
    ]
