# Generated by Django 4.1.3 on 2025-01-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0008_alter_bookers_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookers',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
