# Generated by Django 4.1.3 on 2025-03-06 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0011_rbookers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rbookers',
            old_name='checkin',
            new_name='chein',
        ),
    ]
