# Generated by Django 4.1.3 on 2025-03-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0015_breakfast_dinner_lunch_delete_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakfast',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dinner',
            name='category',
        ),
        migrations.RemoveField(
            model_name='lunch',
            name='category',
        ),
    ]
