# Generated by Django 4.1.3 on 2025-03-09 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0016_remove_breakfast_category_remove_dinner_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalamount', models.CharField(max_length=255)),
                ('quantity', models.CharField(default='', max_length=255)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoapp.breakfast')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoapp.registers')),
            ],
        ),
    ]
