# Generated by Django 4.1.3 on 2025-03-09 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0017_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
    ]
