# Generated by Django 4.1.3 on 2025-03-09 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restoapp', '0018_remove_cart_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='addcart',
        ),
    ]
